### ISSUE TITLE
Ability to use sqg to generate one queue file for multiple programs

### ISSUE THREAD

**Issue by bassmadrigal** [sbopkg/sbopkg#13] opened 2015-11-06 13:58 UTC
Yesterday, I had to build several optional dependencies for kodi (not listed in the REQUIRES line). Since a few had additional dependencies, I relied on the trusty sqg script. I was hoping to output all programs into a single sqf file, however, the option doesn't seem to exist. Maybe it could be added so you can specify an output file to have all the builds outputted to a single file.

`sqg -p libcec libnfs pybluez id3lib rtmpdump avahi lame -o custom.sqf`

The custom.sqf file could be saved in the default queues directory so sbopkg can easily pick it up with a search. Then you can simply install all of them using `sbopkg -i custom`

This could be very handy for people who need a lot of programs compiled (maybe from a large -current update, switching releases, prepping a new computer, or upgrading a core library).

**Comment by McDutchie** [comment] 2016-01-12 22:59
FWIW, `sbodeps` (my companion tool for `sbopkg`, intended to replace `sqg`) does this effortlessly:

    sbodeps -i libcec libnfs pybluez id3lib rtmpdump avahi lame

See https://github.com/McDutchie/sbodeps

**Comment by willysr** [comment] 2017-06-17 20:50
Hi @bassmadrigal 

i think i got this issue fixed in e3cddf3f8f0c1c5d00af2f594988f3271baeca02

```
sqg -p "filezilla qt5-webkit sshblock letsencrypt" -o  

Computers / CPU cores / Max jobs to run
1:local / 2 / 1

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 0 AVG: 0.75s  local:0/4/100%/1.0s 
Done.
root@desktop /home/willysr]# cat /var/lib/sbopkg/queues/custom.sqf 
libfilezilla
wxGTK3
filezilla
libinput
libxkbcommon
qt5
qt5-webkit
perl-TimeDate
perl-File-Tail
perl-yaml
perl-YAML-Syck
perl-Devel-Symdump
perl-Pod-Coverage
perl-Test-Pod-Coverage
perl-Test-Pod
perl-Test-Inter
perl-Date-Manip
perl-Sub-Uplevel
perl-Test-Exception
perl-Carp-Clan
perl-Bit-Vector
perl-Date-Calc
swatch
sshblock
pyparsing
augeas
python-augeas
asn1crypto
six
packaging
idna
ipaddress
enum34
pycparser
cffi
pyasn1
cryptography
pyOpenSSL
ndg_httpsclient
werkzeug
python-configargparse
python-future
python-parsedatetime
psutil
pyrfc3339
zope.interface
zope.event
zope.component
python2-pythondialog
pytz
python-urllib3
python-chardet
python-certifi
python-requests
mock
configobj
letsencrypt
```
is this what you are looking for?

**Comment by bassmadrigal** [comment] 2017-06-18 00:01
That looks like exactly what I was thinking of. Thanks for the excellent addition, Willy!

Jeremy

**Comment by willysr** [comment] 2017-06-18 01:15
It got limitations though. The output filename is always custom, but i think that's fine as you can always generate new custom queue file and rename it as you like.

Closed issue #13

**Comment by swmarc** [comment] 2017-06-19 09:38
https://gist.github.com/swmarc/364fb4b49202264bfe7959f41ce2f079

An alternative implementation without redundant checks for $CUSTOM_QUEUE and
less if/else stuff.
Also, the custom name is freely configurable.

**Comment by willysr** [comment] 2017-06-19 09:49
I tested using SKIP_EMPTY commented and uncommented and both have same effects. Perhaps i should let them stay uncommented?

**Comment by swmarc** [comment] 2017-06-19 09:52
SKIP_EMPTY is required now and shouldn't be commented anymore. It also defaults to lowercase,
since other options are lowercase also. We could accept both if needed.

**Comment by willysr** [comment] 2017-06-19 10:01
based on my testing here, it works well with or without SKIP_EMPTY defined

**Comment by willysr** [comment] 2017-06-19 10:07
So it will break when packages with no deps are queued.

**Comment by swmarc** [comment] 2017-06-19 10:12
sqg just handles 'yes' or 'no', not empty or undefined. SKIP_EMPTY now defaults to 'yes' in sqg.
What's error message regarding that packages without  deps are broken?

**Comment by willysr** [comment] 2017-06-19 10:15
```
sqg -p "rsibreak" -o willy

Computers / CPU cores / Max jobs to run
1:local / 2 / 1

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 1 AVG: 0.00s  local:1/0/100%/0.0s rsibreak: No dep(s) defined for this package.
No queuefile generated.
Uncomment SKIP_EMPTY variable in sqg to change this behavior.
Processing rsibreak.
ETA: 0s Left: 0 AVG: 0.00s  local:0/1/100%/0.0s 
cat: rsibreak.sqf: No such file or directory
Done.
```

**Comment by willysr** [comment] 2017-06-19 10:15
that's what happened when i commented SKIP_EMPTY

**Comment by swmarc** [comment] 2017-06-19 10:17
I see. Missed a check of .sqf files before concatenating.

**Comment by willysr** [comment] 2017-06-19 10:19
if SKIP_EMPTY is a must, then i guess it should be stated like this
SKIP_EMPTY=yes (or no)
instead of 
SKIP_EMPTY=${SKIP_EMPTY:-yes}

**Comment by swmarc** [comment] 2017-06-19 10:22
The issue is that you are not able to overwrite SKIP_EMPTY anymore and editing files in any
bin-directories should be avoided.
I think either we leave it as is and doing a sanity check or moving it into sbopkg.conf?

**Comment by willysr** [comment] 2017-06-19 10:24
sbopkg.conf should be used for global (sbopkg/sqg) usage.
if it's only for sqg, i think it's better to leave it at sqg or functions (IMHO)

**Comment by willysr** [comment] 2017-06-19 11:18
@swmarc : I tried to remove SKIP_EMPTY and it seems to be working fine
see 23696b383bc1d164392531bb9a5adf070440d035 and ba15355444a923a31a9594f5b861ae52e6452574 or probably easier to check [issue-13 branch](https://github.com/sbopkg/sbopkg/tree/issue-13)

**Comment by swmarc** [comment] 2017-06-19 11:40
Alright, but should be rewritable then.
Anyway, there was a bug `sqg-build-queuefile` anyway, evaluating the SKIP_EMPTY value.
Beside that, building a custom queue file now checks if a .sqf file exists.

**Comment by willysr** [comment] 2017-06-19 11:43
i don't see them here. Probably you take the old version?
can you highlight the line from issue-13 branch? I made 3 commits there

**Comment by swmarc** [comment] 2017-06-19 12:10
Sorry, missed one message from you above to read.
I've no additions to your latest commits.

**Comment by willysr** [comment] 2017-06-19 12:21
Thanks, closing #13 again.

**Closed by willysr** 2017-06-19 12:21 UTC
